name: Build & Deploy Go App

on:
  push:
    branches:
      - production

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build Go binary
      run: go build -o main main.go

    - name: Install sftp client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Upload binary via SFTP
      env:
        SFTP_PASS: ${{ secrets.SSH_PASSWORD }}
      run: |
        export SSHPASS="$SFTP_PASS"
        sshpass -e sftp -oBatchMode=no -oStrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
        put main public_html/GO-WMS/main
        bye
        EOF