name: Build & Deploy Go App

on:
  push:
    branches:
      - production

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23' # versi Go yang kamu pakai

    - name: Build Go binary
      run: go build -o main main.go

    - name: Upload binary via SFTP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "main"
        target: "public_html/GO-WMS/main"
        protocol: "sftp"

    - name: (Opsional) Restart app via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          pkill -f ./main || true
          nohup ./main > main.log 2>&1 &