# .github/workflows/deploy.yml
name: Deploy to EasyPanel

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger EasyPanel Deploy
        run: curl -X POST "http://52.63.176.112:3000/api/compose/deploy/48bda4073745cf095b42975c310226861c8e1816d5f944f1"