name: Deploy to Hosting

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Hosting via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd public_html/GO-WMS || { echo "Dir not found"; exit 1; }
          ls -al
          pkill -f ./main || echo "main process not found"
          git status
          git branch
          git pull origin production || echo "Git pull failed"
          go version
          go build -o main main.go || echo "Go build failed"